/**
 * Chooses the data-access transport at startup.
 *
 * - In the **Power Apps host** (deployed app or `npx power-apps run`): the live
 *   {@link SdkDataverseClient} over the generated Dataverse data sources.
 * - **Local `vite dev`** (no host): the offline {@link FakeDataverseClient} with
 *   seeded demo data.
 *
 * Detection uses the SDK host context (`getContext()`), which is populated by
 * the host and throws/returns nothing when running standalone.
 */

import { getContext } from "@microsoft/power-apps/app";
import { getClient } from "@microsoft/power-apps/data";
import type { IContext } from "@microsoft/power-apps/app";
import { AppContainer } from "./container";
import { makeDemoClient, demoConfigs, DEMO_ENTITIES } from "./demoData";
import { SdkDataverseClient } from "@/data/SdkDataverseClient";
import { createStore } from "@/services/PersistedStore";
// Generated by `npx power-apps add-data-source` (entity-set → data-source info):
import { dataSourcesInfo } from "../../.power/schemas/appschemas/dataSourcesInfo";

async function hostContext(): Promise<IContext | null> {
  try {
    // Standalone (plain `vite dev`, no Power host) `getContext()` can hang
    // instead of rejecting — race it with a timeout so we fall back to demo
    // data promptly rather than stalling on the loading screen.
    const timeout = new Promise<null>((resolve) => setTimeout(() => resolve(null), 2500));
    const ctx = await Promise.race([getContext(), timeout]);
    return ctx?.app?.appId ? ctx : null;
  } catch {
    return null;
  }
}

/** logical name (e.g. `account`) → data-source/entity-set name (`accounts`). */
function logicalToEntitySet(): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [entitySet, info] of Object.entries(dataSourcesInfo)) {
    const primaryKey = (info as { primaryKey?: string }).primaryKey ?? "";
    const logical = primaryKey.replace(/id$/, "");
    if (logical) map[logical] = entitySet;
  }
  return map;
}

function createSdkContainer(ctx: IContext): AppContainer {
  const dataClient = getClient(dataSourcesInfo);
  const orgUrl = ctx.app.dataverseOrgUrl?.replace(/\/$/, "") ?? "";
  const map = logicalToEntitySet();

  const client = new SdkDataverseClient(dataClient, {
    apiBaseUrl: orgUrl ? `${orgUrl}/api/data/v9.2/` : "",
    metadataTableFor: (logical) => map[logical] ?? logical,
    whoAmI: async () => ({
      userId: ctx.user.objectId ?? "",
      businessUnitId: "",
      organizationId: ctx.app.environmentId ?? "",
    }),
  });
  const store = createStore(`${ctx.app.environmentId ?? "env"}:${ctx.app.appId ?? "app"}`);
  return new AppContainer(client, demoConfigs(), Object.keys(map), store);
}

export interface Bootstrap {
  container: AppContainer;
  mode: ClientMode;
  /** Dataverse org URL when connected to the host (for the location indicator). */
  orgUrl?: string;
  /** Environment id when connected. */
  environmentId?: string;
}

export async function createContainer(): Promise<Bootstrap> {
  const ctx = await hostContext();
  if (ctx) {
    try {
      return {
        container: createSdkContainer(ctx),
        mode: "sdk",
        orgUrl: ctx.app.dataverseOrgUrl,
        environmentId: ctx.app.environmentId,
      };
    } catch (e) {
      // Fall back to demo data so the app still renders if live init fails.
      console.error("[LookupImportPlus] Live Dataverse init failed:", e);
    }
  }
  return {
    container: new AppContainer(makeDemoClient(), demoConfigs(), DEMO_ENTITIES, createStore("local")),
    mode: "fake",
  };
}

export type ClientMode = "fake" | "sdk";
